spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/pzgc_db?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: hci_root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
      ddl-auto: update  # Hibernate ddl auto (create, create-drop, validate, update)
    show-sql: true

  resources:
    static-locations: classpath:/static/
